-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 7539d8bd1a00a3c1bfd34cdb606d3a6372e83469
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: pretty-format-json
        args:
        - --autofix
        - --top-keys=_id
    -   id: check-symlinks
    -   id: check-yaml
    -   id: detect-private-key
    -   id: requirements-txt-fixer
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: 149e61b7a717945143fe51f010fe1c576e729a9f
    hooks:
    -   id: pep257
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: c25201a00e6b0514370501050cf2a8538ac12270
    hooks:
    -   id: remove-tabs
